name: farm_go_app
description: A farm management and biosecurity application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.0

  # UI & State
  provider: ^6.0.5
  fl_chart: ^0.66.0
  google_maps_flutter: ^2.5.0

  # Utilities
  flutter_local_notifications: ^17.0.0
  intl: ^0.19.0
  timezone: ^0.9.2
  image_picker: ^1.0.4
  permission_handler: ^11.3.1

  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: FreightTextMedium
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf